### ISSUE TITLE
Maquetar e Implementar DB

### ISSUE THREAD

**Issue by v1siond** [loldlm1/AppDelivery#1]
La DB es la base del proyecto, es lo que va a crear el enlace front-end backend, por lo que debe ser lo primero en hacerse junto con los diseños; No es necesario tener TODA la DB lista antes de empezar a programar, pero si las tablas principales para los procesos básicos como registrar, cargar y mostrar clientes, deliverys y empresas.

Originalmente pensamos en las siguientes tablas básicas:

Empresa -> información de la empresa
Menú -> Menú de la empresa
Cliente -> información del cliente
Delivery -> información del delivery
Orden -> tabla que relaciona todos los anteriores.

**Comment by loldlm1** [comment]
Version 1 para el modelado de la Base de Datos DeliveryApp:

```rb
     User model
# - Name : string
# - Email : string
# - Password : string
# - Api_token : string
# - Address : string
# - Role : integer / La verdad no se si esto sea necesario, un usuario puede trabajar y tambien comprar cierto? 

User has many Companies
User has many Orders
User has many Deliveries, through Orders

     Company model
# - Name : string
# - Address : string
# - Restaurant_type : string
# - Description : string

Company belongs to User
Company has many Menus
Company has many Orders
Company has many Deliveries, through Orders

     Menu model
# - Name : string
# - Price : integer
# - Description : string
# - Image : file 
# - Time : integer? 

Menu belongs to Order
Menu belongs to Company

     Delivery model
# - Accepted : boolean
# - delivered : boolean
# - refused : boolean
# - description : string

Delivery belongs to Order

     Order model 
# - invoice : integer / Seria necesaria un ID especial para la orden no? 

Order has one Delivery
Delivery belongs to Company
Delivery belongs to User
Order has many Menus

```

*Esto funcionaria de esta manera:*
- Un usuario podria registrar mas de un restaurante, por lo que tendria un rol de Administrador, tambien tiene muchas ordenes y envios mendiate las ordenes, supongo que habria que crear una modalidad en la que el usuario elija de ser un cliente a un trabajador y solo en este modo le lleguen las notificaciones de cada orden que se hace, del resto no.
- La compañia le pertenece a un usuario y tiene muchos menus, ordenes y envios mediante las ordenes
- El menu le pertenece a la compañia y tambien a la orden
- El envio le pertenece a la orden y por lo campos que describi, puede ser aceptada, rechazada, entregada y una descripcion que la coloca el usuario, de manera positiva o negativa al que hizo la entrega o a la compañia por su comida.
- La orden en efecto, relaciona a todos y seria un envio por orden, pero aqui hay un detalle, una orden podria enviar varios Menus?   

Cualquier cosa puede cambiar, si desean añadir un campo faltante o aportar ideas para el mejor funcionamiento de la DB estaria genial.

**Comment by v1siond** [comment]
This issue was moved to WoWDeliveryApp/deliveryApp#1
